### PR TITLE
First version of postMessage and onmessage algorithms

### PR DESCRIPTION
**Pull request by drott**
Modeled after WebSockets behavior.

Addresses issue #46.

TODO: Fix references to ArrayBuffer, Blob, etc.
TODO: Discuss whether we need "binaryType"
TODO: Check _trusted_ event property. 
TODO: Define presentation origin somewhere.

### CODE REVIEW

**Comment by drott** [comment]
Rawgit HTML version here: https://rawgit.com/drott/presentation-api/postmessage/index.html#posting-a-message-through-presentationsession

**Comment by mfoltzgoogle** [comment]
Thanks for putting this together, comments:

Indent the following to match the rest of the definition.   Also the first instance of 'postMessage' is bold while other declarations are not.

```
// Communication
attribute BinaryType binaryType;
EventHandler onmessage;
void postMessage (DOMString message);
void postMessage (Blob data);
void postMessage (ArrayBuffer data);
void postMessage (ArrayBufferView data);
```

> the data contents of a transmission between two browsing contexts

Does this mean a single invocation of `postMessage()`?  I think it would be permissible for the implementation to fragment transmission (e.g. to meet the requirements of a network transport) of a single message.  Can it be clarified?

> Let presentation message format be the format of that data, one of Text and Binary.

I think of this as a type, not a format; the text data could be sent in a binary format if the implementation chooses.  So maybe: "Let *presentation message type* be the type of that data, one of `text` or `binary`."

> (Set to Binary if data is one of ArrayBuffer or Blob. Set to Text if data is of type DOMString)

This would be clearer as its own step.

> to the remote side, i.e. from opening browsing context to presentation browsing context or vice versa

Maybe just "to the destination browsing context"?  Or have a step that defines the destination context for the data?

>the URL that the opening browsing context and the presenting browsing context have in common.

What if they have no URL in common?

> If the presentation message format is Text, then initialize event's data attribute to the contents of  presentation message data.

...as a DOMString?

**Comment by drott** [comment]
> TODO: Fix references to ArrayBuffer, Blob, etc. …

Added, drott's xref repo updated to include TypedArray spec.

> TODO: Discuss whether we need "binaryType"

Left in for now to emulate WebSocket spec.

> TODO: Check trusted event property.

Reference to trusted event added, isTrusted is true since it's a UA generated event.

> TODO: Define presentation origin somewhere.

Issue #63 created.

> Does this mean a single invocation of postMessage()?
> I think it would be permissible for the implementation to fragment
> transmission (e.g. to meet the requirements of a network transport)
> of a single message. Can it be clarified?

Tried to clarify this by specifying a "data payload" and an implementation specific transport mechanism.

>> presentation message format

> I think of this as a type, not a format;

Changed.

>> (Set to Binary if data is one of ArrayBuffer or Blob. Set to Text if data is of type DOMString)

> This would be clearer as its own step.

Moved to own step.

> Maybe just "to the destination browsing context"? Or have a step that defines the destination context for the data?

Defined destination browsing context in separate step.

> What if they have no URL in common?

See above, created issue #63 to discuss origin relationship.

> ...as a DOMString?

Added mention of type here.

**Comment by mfoltzgoogle** [comment]
LGTM with a few minor fixes:

L1025: format => type
L1052-1070: 
format => type
Binary -> `binary`
Text -> `text`

**Comment by drott** [comment]
Thanks for the thorough review.

**Pull request merged**
