### PR TITLE
Updated version of PR#119: Initial description of session creation and monitoring in presenting

### PR DESCRIPTION
**Pull request by mfoltzgoogle**
Modified version of PR by @obeletski to implement resolution of #34.  Also impacts #19.

### CODE REVIEW

**Comment by mfoltzgoogle** [comment]
@obeleski, please take a look at the updated PR.  I'll plan on merging tomorrow.

**Comment by mfoltzgoogle** [comment]
BTW, the updated spec can be found here:

https://rawgit.com/w3c/presentation-api/obeletski-presenting-context-getsession-getsessions-issue-34/index.html

**Comment by obeletski** [comment]
@mfoltzgoogle, thanks for editing and updating. LGTM.

**Comment by anssiko** [comment]
@mfoltzgoogle Please merge this to make sure participants review the latest as part of the CfC to publish an updated Working Draft. Also please close the originating PR #118 when this lands.

**Pull request merged**
