### PR TITLE
Make the Example section more concise  (Issue #42)

### PR DESCRIPTION
**Pull request by louaybassbouss**
This PR contains new draft of the example section as discussed in issue #42

### CODE REVIEW

**Comment by louaybassbouss** [comment]
Hi Dominik, I just pushed a new version. 

BTW is there another code formatting style with better code highlighting like in some other W3C Specs.

BR

**Comment by drott** [comment]
LGTM, thanks for the quick update.

**Comment by drott** [comment]
> BTW is there another code formatting style with better code highlighting like in some other W3C Specs.

Any ideas about that @anssiko ? If nothing else, we could link ```highlight.js``` for example.

**Comment by anssiko** [comment]
Anolis does not have built-in support for syntax highlighting, while some other spec authoring tools such as ReSpec and Bikeshed do have it.

If we'd enable highlighting it'd be better done at build time. There's a Node.js module for `highlight.js`, so perhaps that is doable with little effort.

**Pull request merged**
