### PR TITLE
Fetch respec over HTTPS

### PR DESCRIPTION
**Pull request by foolip**
This ought to fix mixed content problems on https://w3c.github.io/presentation-api/

### CODE REVIEW

**Comment by mounirlamouri** [comment]
I can't merge but LGTM.

**Comment by tidoust** [comment]
@foolip I'm afraid I broke this while switching to ReSpec. Sorry about that!

Could we rather use a "network-path reference", meaning dropping the `https:` prefix to end up with `//www.w3.org/Tools/respec/respec-w3c-common` so that it works with both schemes?

**Comment by foolip** [comment]
WFM, but I was assuming that people want to edit the file locally, in which case the scheme-relative URL wouldn't work.

**Comment by mounirlamouri** [comment]
Given that it's fine to include https from http, I think we can go with
https only.

**Comment by foolip** [comment]
Thanks, https://w3c.github.io/presentation-api/ now renders as it should!

**Pull request merged**
