### PR TITLE
Replace DOMString with USVString for PresentationRequest URLs.

### PR DESCRIPTION
**Pull request by mfoltzgoogle**
Addresses Issue #361: Use USVString for URLs.

### CODE REVIEW

**Comment by mfoltzgoogle** [comment]
PTAL @annevk who requested the change.

**Comment by mfoltzgoogle** [comment]
Reverted the ID change.

(It seems unlikely that a unique ID generated by the browser will have a lone surrogate, but let's make that a separate issue.)

**Comment by annevk** [comment]
Is the ID transmitted over the wire or serialized in some way? In that case USVString might make sense.

**Comment by mfoltzgoogle** [comment]
Yes, it needs to be serializable as it can be sent to a separate receiving user agent over the network.  UTF-8 can encode lone surrogates, but we don't require that, so that sounds like a reason for using USVString to provide more flexibility.

**Comment by annevk** [comment]
UTF-8 cannot encode lone surrogates. So yes, you should use USVString.

**Pull request merged**
