### PR TITLE
Ignore defaultRequest if presentation disabled by sandbox flag.

### PR DESCRIPTION
**Pull request by mounirlamouri**

### CODE REVIEW

**Comment by mounirlamouri** [comment]
@mfoltzgoogle PTAL.

**Comment by mounirlamouri** [comment]
Fixes #293

**Comment by mfoltzgoogle** [comment]
I might be more specific about what the UA should do if the sandboxing flag is set; as it reads, it seems like the controlling UA can do what it likes.

For example, something like:

> If the sandbox flag is set on the controlling context's document object, then the controlling UA should act as if the default request is not set for that browsing context.

**Comment by anssiko** [comment]
@mounirlamouri to get this into the CR release, could you update the PR considering @mfoltzgoogle's feedback. Thanks!

**Pull request merged**
