### PR TITLE
Added defaultsessionstart and default-presentation <link> to the spec

### PR DESCRIPTION
**Pull request by avayvod**
See https://github.com/w3c/presentation-api/issues/26 for details.

I also fixed the <section> structure of the document which was misaligned and updated xrefs/presentation.json (not sure if I had to do that or not).

### CODE REVIEW

**Comment by avayvod** [comment]
See http://avayvod.github.io/ for the new version of the spec.

**Comment by anssiko** [comment]
Thanks for the PR! Some comments below:

* For "Note: ..." please use `<p class="note">...</p>`

* The new link type "default-presentation" is used in the example, but it is not defined in the normative prose. Please add a new section for this. You can refer to the Link types section [1] in the HTML spec for some inspiration.

* In the "6.6 Interface DefaultSessionStart" section [2] it is said: 

> An event named defaultsessionstart is fired when the UA initiates a presentation on behalf of the page.

We should specify at which stage of the "establish a presentation connection" algorithm [3] the event is fired.

* Could we fire the `defaultsessionstart` event whenever a new session is started, regardless of whether it is UA initiated or a result of `startSession()` or `joinSession()` invocation?

[1] http://www.w3.org/TR/html51/semantics.html#linkTypes
[2] http://avayvod.github.io/#interface-defaultsessionstart
[3] http://avayvod.github.io/#establish-a-presentation-connection

**Comment by mfoltzgoogle** [comment]
@avayvod, comments on the PR.

Overview.src.html:

L397: Instead of adding a Note:, I might phrase as:
> The UA must provide a way to start sending content to the secondary screen.  This may occur at the request of the page or at the request of the UA.

L605: Maybe:
> Handling an event for a UA initiated presentation session example

L611:
> ...allows the page to...

I suggest defining an algorithm for starting a browser initiated presentation session, that initializes session and updates the session database `D`, then chains to 6.4.3 (*Establishing a Presentation Session Connection*).

Do we need to update  *Monitoring the list of available presentation displays* to take into account the default presentation URL?

**Comment by mfoltzgoogle** [comment]
@anssiko, in response to 

> Could we fire the defaultsessionstart event whenever a new session is started, regardless of whether it is UA initiated or a result of startSession() or joinSession() invocation?

We could fire this event in all cases, but the caller would need to handle the duplicate session returned by both `defaultsessionstart` and from resolving the `Promise`s returned by `startSession()` and `joinSession()`.  Do you see an advantage to that?

**Comment by anssiko** [comment]
@mfoltzgoogle Sorry if this was pending for my response, I missed this. Please feel free to rebase and merge.

**Comment by avayvod** [comment]
I believe we could have a generic onsessionstart event then and abandon returning a Promise from start/joinSession resulting in a more unified API and smaller API surface. Not sure it would be convenient for the page because it might have to track what request is being resolved with the new session passed in onstart. Although the page might not care much.

Having a Promise returned for startSession/joinSession is better for error handling though - the page makes a request and either gets a session or gets an error. There's no issue with the timing of when event listener is attached. If we use an event handler to pass the result of startSession/joinSession to the page, we'd have to add onsessionfail, for example.

I think a Promise based API for startSession/joinSession is better.

**Comment by avayvod** [comment]
I'm still working on addressing the comments (slowly). Will try to upload a new pull request today.

**Comment by avayvod** [comment]
I moved the preview of the changed spec to avayvod.github.io/defaultsessionstart.html

**Comment by mfoltzgoogle** [comment]
Pull request looks good; merged.  I will check the issues and close if there is one that is relevant to this spec change.

**Pull request merged**
